### ISSUE TITLE
Please make meeting times in Chronological Order

### ISSUE THREAD

**Issue by jabbate19** [ComputerScienceHouse/CSHMembersPortal#148]
Please it makes me sad :(

<img width="285" alt="image" src="https://github.com/ComputerScienceHouse/CSHMembersPortal/assets/40615740/1b1969e2-b4f3-486e-90f7-8de0a9de8638">

**Comment by Mobmaker55** [comment]
do you happen to know where that is page wise or something

**Comment by Mobmaker55** [comment]
NVM I opened members I'm just STUPID

**Comment by esoccoli** [comment]
Resolved by #150
