### ISSUE TITLE
Update meeting times on the sidebar to match Fall 2024 meeting times

### ISSUE THREAD

**Issue by esoccoli** [ComputerScienceHouse/CSHMembersPortal#161]
This should be as simple as checking the calendar for the day and time of each directorship meeting, and then update a JSON file with those days/times

**Comment by uskYash** [comment]
Hi , I hope you're doing well. I I believe I can contribute effectively, and I'm eager to help resolve it. If it's possible, could you please assign me this task? I would really appreciate the opportunity. Thank you!"

**Comment by esoccoli** [comment]
Resolved by #162
