### ISSUE TITLE
Top logo is broken / missing

### ISSUE THREAD

**Issue by GICodeWarrior** [ComputerScienceHouse/CSHMembersPortal#43]
It is attempting to load from https://members.csh.rit.edu/img/csh_logo_white.png

![top-logo-broken](https://cloud.githubusercontent.com/assets/19803/6102095/db72a050-afe4-11e4-90d6-76d872f86260.png)

**Comment by bencentra** [comment]
The background image is also missing.

Trying to view the image directly gives me a 404: https://members.csh.rit.edu/img/csh_logo_white.png

Trying to view the "img" directory gives me this: https://members.csh.rit.edu/img/. I remember that members portal...

**Comment by bencentra** [comment]
Turns out I never uploaded the images; the .gitignore has an entry for the img/ directory for some reason.

@mbillow should be adding them again, along with some other changes, in the very near future

**Comment by mbillow** [comment]
Issue fixed, assets added.
