### ISSUE TITLE
Webauth Logout Link Broken

### ISSUE THREAD

**Issue by AndrewHanes** [ComputerScienceHouse/CSHMembersPortal#79]
Logout link on members.csh.rit.edu ("Webauth Logout") is a dead link- https://webauth.csh.rit.edu/logout

**Comment by stevenmirabito** [comment]
Yep, this is a known issue and needs to be resolved across all of our services.

For reference, the logout URL for services on Yasuko is: https://members.csh.rit.edu/logout
