### ISSUE TITLE
Plug formatting is not consistent

### ISSUE THREAD

**Issue by sgreene570** [ComputerScienceHouse/CSHMembersPortal#85]
On some monitors (4:3 in my case), plugs extend past the edge of their container.  The plug container should be at least as wide as plugs are. 
![image](https://user-images.githubusercontent.com/17414243/30290589-e24dbcd6-96fd-11e7-8e7c-143b73e6d650.png)

**Comment by stevenmirabito** [comment]
The plug image should actually be responsive to the size of the container, not the other way around.

**Comment by RamZallan** [comment]
`width: 100%;` on the image should fix it up.
